# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ef16c0aebe1b065fcdf503384fc82b71fd0364027a962a7b4b4bae7f8912df5d78b597fade7b366dffd28760257c99773b8198b41604bc5363b5c6d947784e

test:
  secret_key_base: 86060e7f2cf93e6d70f1d580261290d666959ca01dfe41685b1831c9088f7907d57dc67ff45b1b4d61d1f737a5aba281698524917946cdb5309264d81ab17d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
